---
abstract: 'Plugin to Module::Build to build PDL projets'
author:
  - 'Mark Grimes, E<lt>mgrimes@cpan.orgE<gt>'
build_requires: {}
configure_requires:
  Module::Build: 0.40004
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Build-Pluggable-Fortran
provides:
  Module::Build::Pluggable::Fortran:
    file: lib/Module/Build/Pluggable/Fortran.pm
    version: 0.20
requires:
  ExtUtils::F77: 0
  Module::Build::Pluggable::Base: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Module-Build-Pluggable-Fortran
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/mb-pluggable-fortran
version: 0.20
x_test_requires:
  IPC::Cmd: 0
  Test::More: 0.87
